### ISSUE TITLE
How to return result into angularjs?

### ISSUE THREAD

**Issue by digicharan** [mudrd8mz/node-moodle-client#9] opened 2017-04-19 09:57 UTC
Hello,

Thank you for your post. 
I have followed the steps provided and i am getting the result in the console.

Now, instead of printing in console, how can we return  the  result to angular controller file?

Ex: instead of printing like "console.log("Hello %s, welcome to %s", info.fullname, info.sitename);",  I want to return  "info" to angular..

Thank you for your help in advance..
Charan

**Comment by mudrd8mz** [comment] 2017-04-19 10:35
Sorry I'm not an Angular developer but I expect that once you have the data available, it is up to your app to process it further. Closing as not a bug.

**Closed as completed by mudrd8mz** 2017-04-19 10:35 UTC
